const JOBS=[{title:"Frontend Engineer",company:"Nimbus",city:"Bengaluru",type:"Hybrid",cat:"IT & Software",salary:18,days:1},{title:"Product Designer",company:"KitePay",city:"Remote",type:"Remote",cat:"Design",salary:16,days:2},{title:"Sales Executive",company:"Orbit Retail",city:"Mumbai",type:"On-site",cat:"Sales & Marketing",salary:6,days:1},{title:"Staff Nurse",company:"Saffron Health",city:"Delhi",type:"On-site",cat:"Healthcare",salary:5.5,days:3},{title:"Data Analyst",company:"Veda Cloud",city:"Pune",type:"Hybrid",cat:"IT & Software",salary:12,days:2},{title:"CA / Accountant",company:"Aarohi Labs",city:"Ahmedabad",type:"On-site",cat:"Finance",salary:8,days:4},{title:"Content Intern",company:"Jobole Studio",city:"Remote",type:"Remote",cat:"Internship",salary:2.4,days:1},{title:"Ops Associate",company:"Orbit Retail",city:"Hyderabad",type:"On-site",cat:"Operations",salary:4.8,days:5},{title:"Maths Teacher",company:"Vidya Nest",city:"Jaipur",type:"On-site",cat:"Education",salary:4.2,days:2},{title:"React Native Dev",company:"Nimbus",city:"Remote",type:"Remote",cat:"IT & Software",salary:20,days:3},{title:"HR Executive",company:"Saffron Health",city:"Noida",type:"Hybrid",cat:"Operations",salary:5,days:6},{title:"Performance Marketer",company:"KitePay",city:"Gurugram",type:"Hybrid",cat:"Sales & Marketing",salary:11,days:1}];
let activeCat="",query={role:"",city:""};
const grid=document.getElementById("jobsGrid"),jobCount=document.getElementById("jobCount"),hint=document.getElementById("searchHint");
function filtered(){const sort=document.getElementById("sortSelect").value;let list=JOBS.filter(j=>{const roleOk=!query.role||(j.title+j.company+j.cat).toLowerCase().includes(query.role.toLowerCase());const cityOk=!query.city||(j.city+j.type).toLowerCase().includes(query.city.toLowerCase());return roleOk&&cityOk&&(!activeCat||j.cat===activeCat)});return sort==="salary"?[...list].sort((a,b)=>b.salary-a.salary):[...list].sort((a,b)=>a.days-b.days)}
function render(){const list=filtered();jobCount.textContent=list.length+" jobs mili · demo data";grid.innerHTML=list.map(j=>`<article class="job"><div class="top"><span class="badge ${j.type==="Remote"?"remote":""}">${j.type}</span><span class="meta">${j.days}d ago</span></div><h3>${j.title}</h3><p class="meta">${j.company} · ${j.city}</p><p class="salary">₹${j.salary} LPA</p><p class="meta">${j.cat}</p><button class="btn primary" onclick="applyJob('${j.title}')">Apply</button></article>`).join("")||`<p class="meta">Koi job nahi mili.</p>`}
function handleSearch(e){e.preventDefault();query.role=document.getElementById("qRole").value.trim();query.city=document.getElementById("qCity").value.trim();hint.textContent=query.role||query.city?"Results: "+[query.role,query.city].filter(Boolean).join(" · "):"";document.getElementById("jobs").scrollIntoView({behavior:"smooth"});render();return false}
function applyJob(title){openModal("apply",title)}
document.querySelectorAll(".cat").forEach(btn=>btn.addEventListener("click",()=>{const cat=btn.dataset.cat;activeCat=activeCat===cat?"":cat;document.querySelectorAll(".cat").forEach(b=>b.classList.toggle("active",b.dataset.cat===activeCat));render();document.getElementById("jobs").scrollIntoView({behavior:"smooth"})}));
document.getElementById("sortSelect").addEventListener("change",render);
function toggleMenu(){document.querySelector(".nav-links").classList.toggle("open");document.querySelector(".nav-cta").classList.toggle("open")}
function openModal(mode,extra){const title=document.getElementById("modalTitle"),text=document.getElementById("modalText"),extraInp=document.getElementById("mExtra");if(mode==="login"){title.textContent="Login";text.textContent="Demo login.";extraInp.placeholder="Password"}else if(mode==="post"){title.textContent="Job post karo";text.textContent="Company details bhejo.";extraInp.placeholder="Company + role"}else if(mode==="seeker"){title.textContent="Resume drop";text.textContent="Demo form.";extraInp.placeholder="Desired role"}else{title.textContent="Apply — "+(extra||"Job");text.textContent="Demo apply flow.";extraInp.placeholder="LinkedIn / phone"}document.getElementById("modalBg").classList.add("show")}
function closeModal(ev){if(ev===true||ev.target.id==="modalBg")document.getElementById("modalBg").classList.remove("show")}
function submitModal(e){e.preventDefault();alert("Thanks "+document.getElementById("mName").value+"! Demo request note ho gayi.");closeModal(true);e.target.reset();return false}
render();
